# src/main/resources/application.yml 
spring: 
  application: 
    name: blog 
  
  datasource: 
    url: jdbc:postgresql://localhost:5432/blog 
    username: samucael 
    password: ${DB_PASSWORD:2784} 
    driver-class-name: org.postgresql.Driver 
  
  jpa: 
    hibernate: 
      ddl-auto: update     # cria/atualiza tabelas automaticamente (dev) 
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.PostgreSQLDialect 
        format_sql: true 
    show-sql: true         # mostra SQLs no console 
  
  security: 
    user: 
      name: admin 
      password: admin     # apenas para arrancar; vamos sobrescrever 
  
server: 
  port: 8080 
  servlet: 
    context-path: / 
  
logging: 
  level: 
    org.springframework.security: DEBUG